language: python
python:
- '3.7'
env:
- CODECOV_TOKEN="a8345d97-ae52-4ec2-8e30-88040f40363d"
install:
- pip install codecov
- pip install coverage
script:
- python -m unittest discover -v ./ci_play/
- coverage run ./ci_play/test.py
after success: bash <(curl -s https://codecov.io/bash)
